### PR TITLE
[#32] Add CLI options parsing

### LINKED ISSUE #32: Add options parsing and default config dump
# Clarification and motivation

Currently the bot only takes one optional argument - config filename. But we should have some library that whould treat this in a better way, provide help and program description.
Also, like in [xrefcheck](https://github.com/serokell/xrefcheck) we can add a command `dump-config`.

# Acceptance criteria
* Add options parsing using `optparse-applicative`
* Add `dump-config` command for emiting default configuration with all explaining commentaries.

### PR DESCRIPTION
**Pull request by YuriRomanowski**
## Description
Problem: Currently, our program has no CLI infrastructure with program
  description, helps etc. Also, there is no way to dump the default
  config with useful explanations.

Solution: Add optparse-applicative CLI parser that supports the default
  mode (run the Slack timezone bot) and also additional dump-config
  command.

## Related issue(s)

Fixed #32 

#### Related changes (conditional)

- Tests
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

- Documentation
  - [ ] I checked whether I should update the docs and did so if necessary:
    - [README](../tree/master/README.md)
    - Haddock

#### Stylistic guide (mandatory)

- [x] My commits comply with [the policy used in Serokell](https://www.notion.so/serokell/Where-and-how-to-commit-your-work-58f8973a4b3142c8abbd2e6fd5b3a08e).
- [x] My code complies with the [style guide](../tree/master/docs/code-style.md).

### CODE REVIEW

**Review by Martoon-00 — COMMENTED** [review]
Very nice :+1: 

AFAIU you picked the implementation in `xrefcheck` as base? If so, note that there was a [PR](https://github.com/serokell/xrefcheck/pull/257) that improved the stuff. You may or may not include it here.

Also, formatting :smile_cat:

**Comment by Martoon-00** [comment]
Hm, interesting indentation in the commit message.

If you are planning to use it further, I'd recommend writing in Slack (probably into #engeneering channel) and ask how much is it worthy to do so. I think eventually we must use a uniform approach, and I actually see some pros in going with the indentation.

**Review by Martoon-00 — APPROVED** [review]
Looks nice, thank you :+1:

**Comment by YuriRomanowski** [comment]
> Hm, interesting indentation in the commit message.
> 
> If you are planning to use it further, I'd recommend writing in Slack (probably into #engeneering channel) and ask how much is it worthy to do so. I think eventually we must use a uniform approach, and I actually see some pros in going with the indentation.

Hm, that was just a strange fluctuation :smile: I'll reword this commit

**Pull request merged**
